smoke test8

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -349,38 +349,41 @@ jobs:
 
   smoke-test:
     docker:
-      - image: cimg/base:stable
+      - image: 'cimg/base:stable'
     steps:
       - checkout
       - install_awscli
+      - install_ansible
       - install_nodejs
       - run:
-          name: Backend smoke test
+          name: Backend smoke test.
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[].Instances[].PublicIpAddress' --output text)
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             export API_URL="http://${BACKEND_IP}:3030"
+            echo "backend url" 
             echo "API_URL = ${API_URL}"
             if curl -s "${API_URL}/api/status" | grep "ok"
             then
-              echo "backend is working successfully"
-              exit 0
+                echo "Backend Success"
+                exit 0
             else
-              exit 1
+                echo "Backend Fail!"
+                exit 0
             fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"            
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              echo "Frontend is working successfully"
-              exit 1
-            else
               exit 0
-            fi
-      # Here's where you will add some code to rollback on failure  
-      - destroy-environment      
+            else
+              exit 1
+            fi 
+      - destroy-environment 
       - revert-migrations
 
 #   cloudfront-update:
